language: android

sudo: false

env:
  global:
    MALLOC_ARENA_MAX=2
#    JAVA_OPTS="-Xmx2048m -UseGCOverheadLimit"
    GRADLE_OPTS=-Xmx1024m -Dorg.gradle.parallel=false

jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

cache:
  directories:
    - $HOME/.local/opt

before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx2048m"

before_install:
  - ./travis/scripts/install_android_ndk.sh
  - export PATH=$HOME/.local/bin:$PATH

script: ./gradlew build --no-daemon --stacktrace
